sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: mUxddsewFVHfSf/+YZSVFZFv83/7fmylYaGF0MOkIdCYdxTJs8uHp6FYVHVSc1xT+4HgZBrP7y3CLIhhgxNHjFmT1gKvRbVTFOSk3Pt8FyTO/+b+10/RA5FndCS3+24Ri2yxUYU+uDNysjrozCkHEfpvirfArHfijBqusMvzkuoZ4czS5POSl1kk/RO4Wd/8T7wN2pr6FCB2HumW+9Z8Wx4WDHFZeaBUu9HAv/V/rfTO5GIvyxT0bnWy69y0Z9WS3ugsRmmQPtx3L9swGWrl26wTfz/Oaz4/uhHVc5mN4+dl/yPBhSbTvr3Fjt+A1Nnwn+/5hnn5CY/2hPR+SCouDjeotMPQgoYIZ18WAqz0/pQm5UfDOBGdu0c5n0epwgHA0BtTI2xh3aDZxVscuPcD6OVdEltfrzAst981s2OL939pZx/yMiZLPexg1mKSUffovTTw718e7wJMs0+9xJ9skbJlZ96l0FU4OinwQ5KbRC8UP+ulUk5shtG/ZIcyOe0xLdAOUWynWdrOpQMdza+MBnTdds/Z+098IQoOKucWV+Dmdh8NyHE9pa1uuhgKYwBpmhnDPFACB1zr5yJzm255Bg+yK9SYu5HriaNta/dHbuqRQZx/PjYCLqOQY/HujRcbymE2MU4D56MqE5x/+MsT9YTOUyAIxUgHPLBIZLQpAy8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Zen-and-the-Art-of-the-Internet_34
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy